name: CI Shellcheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Shellcheck
        run: sudo apt update && sudo apt install shellcheck

      - name: Run shellcheck of dnschk.sh
        run: shellcheck dnschk.sh
